### ISSUE TITLE
Enabling of cemeteries?

### ISSUE THREAD

**Issue by manulopezw** [AvarionMC/graves#24] opened 2024-06-20 04:30 UTC
I see that the addon includes cementeries, burialgrounds, graveyards, churchyards and necropolis
Is there any difference between them?

**Comment by svaningelgem** [comment] 2024-06-20 05:27
From what I could glance from the code is that this part wasn't finished by ranull. I can only surmise that the graves would spawn in a designated area.

Feel free to go through the code and enable it? 😁

**Comment by svaningelgem** [comment] 2024-07-07 08:00
Duplicate of #9

**Closed by svaningelgem** 2024-07-07 08:00 UTC
Labels: help wanted
